version: '3.1'
volumes:
  mysql-db: {}
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=test_message
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql-db:/var/lib/mysql/data
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
