version: '3.1'
volumes:
  mysql-db: {}
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '33060:3306'
    environment:
      - MYSQL_DATABASE=board-app
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql-db:/var/lib/mysql
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
